name: test-coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: covr

      - name: Test Coverage
        run: covr::codecov()
        shell: Rscript {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

