# Workflow for test coverage using covr + codecov
on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
        name: Install dependencies

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            type = "tests",
            path = ".",
            clean = FALSE
          )
          print(cov)
          covr::to_cobertura(cov, file = "cobertura.xml")
        shell: Rscript {0}

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./cobertura.xml
          plugins: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          find "${{ runner.temp }}/package" -name 'testthat.Rout*' -exec cat '{}' ';' || true
        shell: bash

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package